### ISSUE TITLE
Support bundler such as Webpack, Browserify and Rollup

### ISSUE THREAD

**Issue by flowersinthesand** [cettia/cettia-javascript-client#12]
Recently my team launched a new project based on webpack, react and so on. It seems that a module available on npm can work with webpack but I'm not sure yet.

https://webpack.github.io/

**Comment by DDKnoll** [comment]
The problem is that it assumes the browser doesn't have module loaders, so it tries polyfilling that stuff.  All the browser needs to polyfill are these:

```
window.msgpack = require("msgpack-lite");
window.traverse = require("traverse");
```

**Comment by flowersinthesand** [comment]
Then, what should be done to import those external modules to use cettia with webpack?

**Comment by DDKnoll** [comment]
I made a new build process that creates a separate browser bundle with eslint:
https://github.com/cettia/cettia-javascript-client/pull/14

It should work with webpack/browserify/rollup or whatever else.

**Comment by flowersinthesand** [comment]
* [ ] Write a webpack example in https://github.com/cettia/cettia-examples
