### ISSUE TITLE
Release needed for webpack compatible version

### ISSUE THREAD

**Issue by DDKnoll** [cettia/cettia-javascript-client#16]
Hey Donghwan,
We should get a new point release for the javascript client. We should also get this updated version up on NPM so that people can follow the Readme on github for installation.

**Comment by flowersinthesand** [comment]
Ah, sorry for the inactivity. Could you take a look at https://github.com/cettia/cettia-javascript-client/pull/14#issuecomment-262263383?

I just updated #15 so http://jsbin.com/huxifaxone/edit?html,js,console is the correct link for manual tests on browser

**Comment by flowersinthesand** [comment]
Thanks for the notice I just released it  http://cettia.io/blog/cettia-javascript-client-1-0-0-beta2-released/
