### ISSUE TITLE
After a device has been woken up from suspend mode, a reconnect leads to a HeartbeatFailedException

### ISSUE THREAD

**Issue by dozed** [cettia/cettia-javascript-client#2]
Using the `DefaultServer` from cettia-server, the server disconnects the client and the client is then in an infinite-cycle trying to reconnect. It seems the client does wait too long to send a heartbeat, or the server timer expires too early. So this looks like some kind of timer issue.

```
io.cettia.HeartbeatFailedException
    at io.cettia.DefaultServer$DefaultServerSocket$8.run(DefaultServer.java:381)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
```

Also what is the meaning of _heartbeat vs. hearbeat?

A related issue:

Also it seems when reconnecting that sometimes there are two sockets open at the same time in the same browser tab (leading to weird message transport). Here is a screenshot of the chrome network tab showing the problem with two open sockets:

![image](https://cloud.githubusercontent.com/assets/239058/7539198/a8be40d6-f5a5-11e4-9e0a-4ae438742ba6.png)

And here is another example where one socket receives multiple `chat` message which have been sent from other sockets (there is only this browser tab connected):

![image](https://cloud.githubusercontent.com/assets/239058/7539487/922f6ffa-f5a7-11e4-8e40-5600ff95ece7.png)

I would expect a socket to only open when the other socket has been closed.

**Comment by flowersinthesand** [comment]
It looks like some condition breaks client-side socket's life cycle so the first thing is to find out that condition. But... I'm busy with the day job now unlike when I was writing this alpha1. So could you share a test case (A maven project on GitHub would be best) for me to reproduce the issue easily?

> Also what is the meaning of _heartbeat vs. hearbeat?

`heartbeat` explanation from http://cettia.io/projects/cettia-java-server/1.0.0-Alpha1/reference/#heartbeat

> An heartbeat interval value in milliseconds. An opened socket in client continuously sends an heartbeat event to the server each time the value has elapsed. Actually, the socket sends the event **5 seconds** before the heartbeat timer expires to wait the server's echo. If the event echoes back within **5 seconds**, the socket reset the timer. Otherwise, both client and server fires the close event. For that reason, the value must be larger than **`5000`**. The default value is `20000`.

The above 5 seconds is the default value of `_heartbeat`. (As `_heartbeat` is internal unlike `heartbeat`, I didn't document it.) Also you can see how they work in client through [reference implementation](http://cettia.io/projects/cettia-protocol/1.0.0-Alpha1/docs/socket.html#section-54).

**Comment by flowersinthesand** [comment]
@dozed As this issue might affect [offline application](https://groups.google.com/d/msg/cettia/1dGafgNDLpg/IkcEkV-JcMMJ) feature, I'd like to make sure that before starting to work on it. Could you share how to reproduce the issue especially 'After a device has been woken up from suspend mode'?

**Comment by flowersinthesand** [comment]
Closed as inactive.
